### ISSUE TITLE
tsdb.timestamp.resolution

### ISSUE THREAD

**Issue by mkohns** [ytyou/ticktock#24]
HI!

Great Job here! I like it.
One question:
- I am running latest code
- 
- I put data in with timestamp in milliseconds
- metrics have been created - but empty
- I specified tsdb.timestamp.resolution to milliseconds (in the conf file)
- I deleted all data and restarted with new config.
- When I put data in - and provide timestamp in milliseconds - this works now!
- But - they are still saved in ticktock as seconds. 
- When I query them - I get

[{"metric":"boiler_data_ww.wwcurtemp","tags":{"host":"BUDERUS"},"aggregateTags":[],"dps":{"1666436125":52.7999999999999972,"1666436135":52.7000000000000028,"1666436145":52.7000000000000028,"1666436155":52.7999999999999972,"1666436165":52.7999999999999972,"1666436175":52.7999999999999972,"1666436185":52.7999999999999972,"1666436195":52.7999999999999972,"1666436205":52.7999999999999972,"1666436215":52.7999999999999972,"1666436225":52.7999999999999972}}]%

What am I doing wrong.
My expectation was, that ticktock also saves them in millis, and not only accepting them and rounding.

**Comment by ytyou** [comment]
When query, you need to specifiy msResolution=true (as described in http://opentsdb.net/docs/build/html/api_http/query/index.html). If you've already done that, then it's a bug. Please let us know. Thanks.

**Comment by mkohns** [comment]
Great! I will Test and give Feedback! Thanks for the fast response!

**Comment by ylin30** [comment]
@mkohns here is an example:

Without msResolution=true:
```
[Yi-MBP ticktock (dev2)]$ curl -s 'http://192.168.1.15:6182/api/query?m=avg:ticktock.mem.reusable.total:&start=1666458310&end=1666458312'
[{"metric":"ticktock.mem.reusable.total","tags":{},"aggregateTags":["type"],"dps":{"1666458311":7171.6756756756758477}}]
```

With msResolution=true:
```
[Yi-MBP ticktock (dev2)]$ curl -s 'http://192.168.1.15:6182/api/query?m=avg:ticktock.mem.reusable.total:&start=1666458310&end=1666458312&msResolution=true'
[{"metric":"ticktock.mem.reusable.total","tags":{},"aggregateTags":["type"],"dps":{"1666458311425":7171.6756756756758477}}]
```
