### ISSUE TITLE
API  returns 404 or 500

### ISSUE THREAD

**Issue by mzy2240** [ytyou/ticktock#28]
Trying to send data from home assistant to ticktock via the [RESTful command](https://www.home-assistant.io/integrations/rest_command/), however the API keeps returning 404 (when method=put) or 500 (method=post). This is my payload:
```shell
b'put cpu _usage 1674096240.256369 0'
```
with content type `application/x-www-form-urlencoded`.

Do we need to create the table/metric in advance?

**Comment by mzy2240** [comment]
Passed the ping pong test, so should not be port or db issue.

**Comment by ytyou** [comment]
Please set the log.level to 'HTTP'; run the same command; and then send us the log file. Thank you.

**Comment by mzy2240** [comment]
> First, I would like to point out that your payload has some format problems. There is a space between "cpu" and "_usage". I guess your metric is supposed to be "cpu_usage".

Nice catch! That is a typo when submit the issue, not the actual payload. Sorry about that!



> Second, according to Opentsdb API standard (http://opentsdb.net/docs/build/html/user_guide/writing/index.html), each data point must come with at least one tag (e.g., "host=host1" at the end).
> 
> Third, the timestamp`1674096240.256369` looks weird to me. It is supposed to be a long.

These two might be the actual cost. Will give another try when the new patch released. Thanks!

**Comment by ylin30** [comment]
@mzy2240 v0.10.2 has been released in main branch. Please try it out. Here is the put and query commands for your example data.

```
ylin30@yi-IdeaPad:~$ curl -v -XPOST 'http://localhost:6182/api/put' -d 'put cpu_usage 1674096240.256369 0'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:6182...
...
 HTTP/1.1 200 OK
 Content-Length: 0
 Content-Type: text/plain
ylin30@yi-IdeaPad:~$ curl -v 'http://localhost:6182/api/query?start=1674096200&m=avg:1m-avg:cpu_usage'
*   Trying 127.0.0.1:6182...
...
 HTTP/1.1 200 OK
 Content-Type: application/json
 Content-Length: 78

* Connection #0 to host localhost left intact
[{"metric":"cpu_usage","tags":{},"aggregateTags":[],"dps":{"1674096240":0.0}}]

```

If you have any issues, very welcome to contact us. 

Again, thanks for making TT better.

**Comment by mzy2240** [comment]
Thanks! Keep up the great works!
