### ISSUE TITLE
change config has no effect on log location

### ISSUE THREAD

**Issue by mzy2240** [ytyou/ticktock#30]
log still points to `/var/log/ticktock.log` even after changing to other location in the config.
version 0.10.2

**Comment by mzy2240** [comment]
this is the command I am using to run:
`bin/tt -c conf/tt.conf`
tt.conf has been modified in advance

**Comment by ylin30** [comment]
What does the output of 'bin/tt -c conf/tt.conf' say? E.g., 

```
ticktock@tt-dev:~/ticktock$ ./bin/tt -c conf/tt.conf &
[1] 531
ticktock@tt-dev:~/ticktock$  TickTock v0.10.2,  Maintained by
 Yongtao You (yongtao.you@gmail.com) and Yi Lin (ylin30@gmail.com).
 This program comes with ABSOLUTELY NO WARRANTY. It is free software,
 and you are welcome to redistribute it under certain conditions.
 For details, see <https://www.gnu.org/licenses/>.
Writing to log file: /home/ticktock/tmp/log/ticktock.log

ticktock@tt-dev:~/ticktock$
```

You can try this cmd. Any config which are not default will be printed out. 

```
ticktock@tt-dev:~/ticktock$ ./admin/config.sh
{
  "append.log.dir": "/home/ticktock/tmp/append",
  "http.listener.count": "4",
  "log.file": "/home/ticktock/tmp/log/ticktock.log",
  "log.level": "INFO",
  "tcp.buffer.size": "128kb",
  "tcp.listener.count": "4",
  "tsdb.compact.frequency": "0sec",
  "tsdb.compressor.version": "3",
  "tsdb.data.dir": "/home/ticktock/tmp/data",
  "tsdb.flush.frequency": "1min",
  "tsdb.gc.frequency": "5min",
  "tsdb.page.count": "655360",
  "tsdb.page.size": "128b",
  "tsdb.self_meter.enabled": "false",
  "tsdb.thrashing.threshold": "2min"
}
ticktock@tt-dev:~/ticktock$
```

**Comment by mzy2240** [comment]
```khadas@khadas-vim3:~/ticktock$ ./bin/tt -c conf/tt.conf
 TickTock v0.10.2,  Maintained by
 Yongtao You (yongtao.you@gmail.com) and Yi Lin (ylin30@gmail.com).
 This program comes with ABSOLUTELY NO WARRANTY. It is free software,
 and you are welcome to redistribute it under certain conditions.
 For details, see <https://www.gnu.org/licenses/>.
Failed to open file /var/log/ticktock.log for writing: 13
2023-01-20 19:49:38.785 [INFO] [main] TickTock version: 0.10.2, on khadas-vim3, pid: 30739
```

**Comment by mzy2240** [comment]
> ticktock@tt-dev:~/ticktock$ ./admin/config.sh

Nothing returns

**Comment by ylin30** [comment]
hm, looks like that your conf/tt.conf is the original one. Can you send me your copy?

**Comment by mzy2240** [comment]
I can confirm data is received by db and could query the data out from db. So it is working as expected with home assistant. The only issue left is the log.

**Comment by ylin30** [comment]
Can you do a git status and git diff? It may show what has been changed in your config.

**Comment by mzy2240** [comment]
![Screen Shot 2023-01-20 at 7 57 40 PM](https://user-images.githubusercontent.com/18620336/213836103-09f5934e-9abc-4634-9409-e2cc40388eff.png)

**Comment by mzy2240** [comment]
![Screen Shot 2023-01-20 at 7 58 48 PM](https://user-images.githubusercontent.com/18620336/213836294-7fcef416-40df-46cc-aa3e-bf8cf64122fc.png)

**Comment by ylin30** [comment]
oh, you have a ';' in the front of "log.file=/home/khadas/....". 

Remove the ';' (it means commenting out). It will work.

**Comment by ylin30** [comment]
Still puzzling me what your cmd './admin/config.sh' returns nothing?

**Comment by mzy2240** [comment]
Is admin access needed?

**Comment by mzy2240** [comment]
> oh, you have a ';' in the front of "log.file=/home/khadas/....".
> 
> Remove the ';' (it means commenting out). It will work.

Now no any error occurs.

**Comment by mzy2240** [comment]
> Still puzzling me what your cmd './admin/config.sh' returns nothing?

khadas@khadas-vim3:~/ticktock$ ./admin/config.sh

khadas@khadas-vim3:~/ticktock$

**Comment by ylin30** [comment]
hm. Looks like your TT process is dead. Can you do './admin/ping.sh'? It is supposed to return a 'pong' if alive.

**Comment by mzy2240** [comment]
> ./admin/ping.sh

Still nothing returned.

**Comment by mzy2240** [comment]
NVM. I figured it out. I am running ticktock from a live ssh session, and everytime when I ran `./admin/ping.sh` or `./admin/config.sh`, I always stop the ticktock instance first ...
