### ISSUE TITLE
Docs for Docker environment variables/cmnd lines options for volume storage etc ?

### ISSUE THREAD

**Issue by craigcurtin-dev** [ytyou/ticktock#66]
Hey Guys,

Not seeing anything in the Docs about what docker environment variables you support and options for redirecting data storage (volumes) outside of the container 

Can you point me to the docs on this please ?

I have played with the demo container but that appears to store all data within the container and is not persistent

Craig

**Comment by ylin30** [comment]
There is a docker option, -v, which maps a host volume to a volume inside docker. You can check docker doc for references. I will add an example in doc later.Sent from my iPhoneOn Jan 24, 2024, at 3:27 PM, craigcurtin-dev ***@***.***> wrote:﻿
Hey Guys,
Not seeing anything in the Docs about what docker environment variables you support and options for redirecting data storage (volumes) outside of the container
Can you point me to the docs on this please ?
I have played with the demo container but that appears to store all data within the container and is not persistent
Craig

**Comment by ylin30** [comment]
@craigcurtin-dev I just created a [doc](https://github.com/ytyou/ticktock/wiki/Docker-FAQ-&-Examples) for the issue. Let me know if any questions.

**Comment by craigcurtin-dev** [comment]
Will do thanks

Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
