### ISSUE TITLE
unrecognized option '--http.request.format'

### ISSUE THREAD

**Issue by FedeBev** [ytyou/ticktock#70]
Hi there

running the following command from the doc
```shell
docker run -d --name ticktock -h ticktock -p 6182:6182 -p 6181:6181 --cpus 1 -m 8GB --memory-reservation 6GB ytyou/ticktock:latest --tsdb.timestamp.resolution millisecond --http.request.format json
```

I get the following error

```shell
/opt/ticktock/bin/ticktock: unrecognized option '--http.request.format'
```

Any idea?

Thanks

**Comment by ylin30** [comment]
Hi @FedeBev , `http.request.format` is not longer needed in latest versions. Sorry we don't update the wiki yet. Please run the cmd without ` --http.request.format json`. TT will recognize both json and plain formats of put requests automatically now.

**Comment by ylin30** [comment]
Also FYI, some less-used configs are not supported as arguments in starting command line, which may end up with the `unrecognized option...` error as you saw above. Users have to specify them in conf (e.g., conf/tt.conf) explicitly. I believe `http.request.format` is one of those.

I will also update wiki. Sorry for the confusion.

**Comment by ylin30** [comment]
Done updating the wiki.

**Comment by ylin30** [comment]
@FedeBev Did u have a chance to try it out? Pls don't hesitate to ask any questions.
