### ISSUE TITLE
OSX Build

### ISSUE THREAD

**Issue by kwando** [ytyou/ticktock#72]
Any chance of getting this to run on OSX with apple silicon?

**Comment by ylin30** [comment]
Hm in theory it should be runnable in arm-based arch. Let me try first.

**Comment by kwando** [comment]
I got the beta running on my pi zero (downloaded the binary).

On my Mac I tried to use the docker image. I can get it to boot with the `--platform linux/amd64` flag but the ticktock server is just spinning at 100% CPU and is not responding on the ports.

Thanks for making this softare available, I'm using It to record sensordata on my sailboat and it seems to work pretty well so far. The documentation is a bit sparse and there seems to be several admin commands that suggest there is functionality not even mentioned in the docs.

**Comment by ylin30** [comment]
Unfortunately TT uses many Linux specific stuff so it won't even compile in OSX. We don't think it would be a easy change.

I used docker to run TT in my Mac(x64). cpu is just normal. I didn't use the flag you mentioned. You may want to try without the flag if possible. What version of TT and Mac OS do you use?

**Comment by kwando** [comment]
I'm running on 14.4.1 and running the image with Orbstack. The flag doesnt seem to have an effect other than silencing the error. Can still see ticktock running 100% of a core inside the container. I tried docker desktop too but doest seem to run either. It is not taking up 100% of a core though but the server is not responding on the ports either, `healthcheck.sh` is returning `1` .
```
❯ docker run -d --name ticktock -p 6181-6182:6181-6182 -p 6181:6181/udp ytyou/ticktock:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
6a1032d4405c7ee62884c03fee27308615d94e209f5a296c580f722f146fe5c8
```
Image ID
`sha256:6c0b254dc58bfd8379939cf2a385e8e8101ec50c6b63e5a336d3e91fcd8f9ff4` (0.20.0-beta)

**Comment by ylin30** [comment]
I never use Orbstack and I use the default docker Desktop for MacOS. I am using MacOS 13.0, M1 chip. The TT docker runs fine with the 0.20.0-beta image. 

```
jianningmao@Jiannings-MacBook-Air ~ % docker run -d -p 6180-6183:6180-6183 -p 6181:6181/udp ytyou/ticktock:latest 

Unable to find image 'ytyou/ticktock:latest' locally
latest: Pulling from ytyou/ticktock
76769433fd8a: Pull complete 
57b4bc54a1e7: Pull complete 
74185d7e1013: Pull complete 
4d10431ea0ce: Pull complete 
431b35b5da79: Pull complete 
b9e2b1adcfe3: Pull complete 
3239fd780c72: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:427f43d2cfa71f5253512cf1c32e31f1cdd83ea53159c37ddd90200d91dd5a69
Status: Downloaded newer image for ytyou/ticktock:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
efec7188387d64cd81a141ff64a7dd3adec50b892b9d8cae14bc4c1f23bb63e9
jianningmao@Jiannings-MacBook-Air ~ % docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                             PORTS                                                      NAMES
efec7188387d   ytyou/ticktock:latest   "/opt/ticktock/scrip…"   16 seconds ago   Up 15 seconds (health: starting)   0.0.0.0:6180-6183->6180-6183/tcp, 0.0.0.0:6181->6181/udp   funny_golick
jianningmao@Jiannings-MacBook-Air ~ % curl -XPOST "http://127.0.0.1:6182/api/admin?cmd=ping"
pong%                                        
```

I see the warning you mentioned without the flag. It seems no harm. CPU usage is less than 1% if no incoming metrics.

![dockerImg](https://github.com/user-attachments/assets/12b1b1b7-42f8-43da-b71c-2bee07c59fa2)

I suspect you might be using an old image since your image ID `sha256:6c0b...` doesn't match the one in docker hub (`sha256:427f..`). Can you remove the image (`docker rmi <imageID>`) and retry?

Also you can view the ticktock log within a docker to see if any warning or errors. The log path within the docker is:

`nano /var/lib/ticktock/log/ticktock.log`

**Comment by kwando** [comment]
I got the same image you have now, but still the same issue. Probably something with OrbStack then. I got it running on a VM instead and that is good enough for my purposes (local development) :)

**Comment by kwando** [comment]
Thanks for taking your time and help me look into this! Much appreciated :)
