### ISSUE TITLE
Database corrupted after accessed by browser

### ISSUE THREAD

**Issue by nonix** [ytyou/ticktock#79]
Hi, I have accidently pointed browser to the port of TickTock TSDB and it seems corrupted the data store. Now the db won't start. If you like I can provide some traces ...
However, I think it would be good to have some safe guards in place to avoid corruption on wrong qry syntax and/or not implemented queries.
N.

**Comment by ytyou** [comment]
Could you please send us the HTTP request that caused all of this? Plus the traces? Thanks. We will add some protections.

**Comment by ylin30** [comment]
We do have some safeguards in place but obviously it is not enough. It is serious that the DB doesn't restart. Could you please help us in providing repro steps, traces, logs, corrupted db data, etc?  Thx.

**Comment by nonix** [comment]
[ticktock.zip](https://github.com/user-attachments/files/18140700/ticktock.zip)

Let me know if I can help more.

**Comment by ytyou** [comment]
@nonix Thanks for the information. We will add some more protections.

BTW, if you delete everything in file `datat/ts` except the first 3 lines, the TickTockDB should start. Like this:

\# ticktockdb.0.20.1
temp sensor=primotop venkovni=0 vnitrni=1
power sensor=primotop state=2

**Comment by ytyou** [comment]
More protections added in the latest release (v0.20.5). Thanks!
