### ISSUE TITLE
crash on low memory

### ISSUE THREAD

**Issue by thomasrunge** [ytyou/ticktock#9]
I'm running ticktock on a Raspberry PI zero. Memory is constrained. After some days on collecting data ticktock crashes. But not just a simple crash or core dump, it rotates on "[tcp_1_task_0] Interrupted, shutting down...". So, the process never ends and fills the log file quite fast.

So, could we please fix the wrong crash handling. And memory handling has room for improvement, too.

Other that that: thank you for ticktock!

**Comment by ytyou** [comment]
We have fixed an issue about mishandling of interrupts in our latest version, although it might not be the same one that you encountered. At least it should not fill up log files anymore. What version are you running? Thanks for reporting the bug.

**Comment by ytyou** [comment]
Fixed the wrong crash handling in v0.3.2. Still working on improving memory management.

**Comment by thomasrunge** [comment]
This seems to be fixed now. Thank you.
